language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
before_script:
    - npm install -g pegjs
script:
    - pegjs -o src/assets/js/lpParser.js src/assets/grammar/grammar.pegjs
    - npm run test
    - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  github-token: $GITHUB_TOKEN
  on:
    branch: master