language: node_js
node_js:
  - "stable"
install:
  - npm install
cache:
  directories:
    - "node_modules"
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master